/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EntityId = IDL.Text;
export const AddRetroMessageInput = IDL.Record({
  'content' : IDL.Text,
  'session_id' : EntityId,
  'role' : IDL.Text,
});
export const RetroSessionStatus = IDL.Variant({
  'active' : IDL.Null,
  'completed' : IDL.Null,
});
export const UserId = IDL.Text;
export const Timestamp = IDL.Nat64;
export const ConversationEntry = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'timestamp' : Timestamp,
});
export const ActivityStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'retroactive' : IDL.Null,
  'ongoing' : IDL.Null,
});
export const EligibilityLabel = IDL.Variant({
  'borderline' : IDL.Null,
  'ineligible' : IDL.Null,
  'eligible' : IDL.Null,
});
export const FourPartTestResult = IDL.Record({
  'elimination_of_uncertainty' : IDL.Bool,
  'permitted_purpose' : IDL.Bool,
  'notes' : IDL.Text,
  'technological_in_nature' : IDL.Bool,
  'process_of_experimentation' : IDL.Bool,
});
export const RDActivity = IDL.Record({
  'id' : EntityId,
  'status' : ActivityStatus,
  'activity_type' : ActivityType,
  'user_principal' : UserId,
  'title' : IDL.Text,
  'updated_at' : Timestamp,
  'content_hash' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'program_id' : IDL.Opt(EntityId),
  'description' : IDL.Text,
  'end_date' : IDL.Opt(IDL.Text),
  'eligibility_label' : EligibilityLabel,
  'created_at' : Timestamp,
  'eligibility_score' : IDL.Float64,
  'quantum_adjusted_score' : IDL.Float64,
  'start_date' : IDL.Text,
  'admin_notes' : IDL.Opt(IDL.Text),
  'agent_reasoning' : IDL.Text,
  'hours_spent' : IDL.Float64,
  'four_part_test_result' : FourPartTestResult,
});
export const RetroSession = IDL.Record({
  'id' : EntityId,
  'status' : RetroSessionStatus,
  'user_principal' : UserId,
  'updated_at' : Timestamp,
  'time_range_end' : IDL.Text,
  'conversation' : IDL.Vec(ConversationEntry),
  'created_at' : Timestamp,
  'candidate_activities' : IDL.Vec(RDActivity),
  'time_range_start' : IDL.Text,
});
export const ProgramStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const RNDProgram = IDL.Record({
  'id' : EntityId,
  'status' : ProgramStatus,
  'updated_at' : Timestamp,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'created_at' : Timestamp,
  'irc_section' : IDL.Text,
});
export const EnrollmentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Enrollment = IDL.Record({
  'id' : EntityId,
  'status' : EnrollmentStatus,
  'user_principal' : UserId,
  'program_id' : EntityId,
  'enrolled_at' : Timestamp,
  'reviewed_at' : IDL.Opt(Timestamp),
  'reviewed_by' : IDL.Opt(UserId),
  'review_notes' : IDL.Opt(IDL.Text),
});
export const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
export const UserProfile = IDL.Record({
  'updated_at' : Timestamp,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : IDL.Opt(IDL.Text),
  'principal_id' : UserId,
});
export const CreateActivityInput = IDL.Record({
  'activity_type' : ActivityType,
  'title' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'program_id' : IDL.Opt(EntityId),
  'description' : IDL.Text,
  'end_date' : IDL.Opt(IDL.Text),
  'start_date' : IDL.Text,
  'hours_spent' : IDL.Float64,
});
export const Recommendation = IDL.Variant({
  'reject' : IDL.Null,
  'approve' : IDL.Null,
  'more_info' : IDL.Null,
});
export const AdminSuggestion = IDL.Record({
  'notes' : IDL.Text,
  'recommendation' : Recommendation,
  'confidence' : IDL.Nat,
});
export const ClassificationResult = IDL.Record({
  'eligibility_label' : EligibilityLabel,
  'eligibility_score' : IDL.Float64,
  'quantum_adjusted_score' : IDL.Float64,
  'four_part_test' : FourPartTestResult,
  'suggested_tags' : IDL.Vec(IDL.Text),
  'admin_suggestion' : AdminSuggestion,
  'agent_reasoning' : IDL.Text,
});
export const CreateActivityResult = IDL.Record({
  'activity' : RDActivity,
  'classification' : ClassificationResult,
});
export const MetricEntry = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const ExperimentOutcome = IDL.Variant({
  'failure' : IDL.Null,
  'inconclusive' : IDL.Null,
  'success' : IDL.Null,
});
export const CreateExperimentInput = IDL.Record({
  'method' : IDL.Text,
  'metrics' : IDL.Vec(MetricEntry),
  'linked_activity_id' : IDL.Opt(EntityId),
  'program_id' : IDL.Opt(EntityId),
  'hypothesis' : IDL.Text,
  'results_summary' : IDL.Text,
  'outcome' : ExperimentOutcome,
});
export const Experiment = IDL.Record({
  'id' : EntityId,
  'method' : IDL.Text,
  'user_principal' : UserId,
  'updated_at' : Timestamp,
  'metrics' : IDL.Vec(MetricEntry),
  'linked_activity_id' : IDL.Opt(EntityId),
  'program_id' : IDL.Opt(EntityId),
  'hypothesis' : IDL.Text,
  'created_at' : Timestamp,
  'results_summary' : IDL.Text,
  'outcome' : ExperimentOutcome,
});
export const ReportScope = IDL.Variant({
  'user' : IDL.Null,
  'global' : IDL.Null,
});
export const Report = IDL.Record({
  'id' : EntityId,
  'period_end' : IDL.Text,
  'activity_ids' : IDL.Vec(EntityId),
  'generated_at' : Timestamp,
  'period_start' : IDL.Text,
  'eligible_hours' : IDL.Float64,
  'scope' : ReportScope,
  'total_hours' : IDL.Float64,
  'breakdown_borderline' : IDL.Nat,
  'breakdown_ineligible' : IDL.Nat,
  'estimated_qre_value' : IDL.Float64,
  'breakdown_eligible' : IDL.Nat,
});
export const AuditEntry = IDL.Record({
  'id' : EntityId,
  'action' : IDL.Text,
  'timestamp' : Timestamp,
  'actor_principal' : UserId,
  'entity_id' : EntityId,
  'entity_type' : IDL.Text,
});
export const GlobalStats = IDL.Record({
  'total_programs' : IDL.Nat,
  'total_users' : IDL.Nat,
  'pending_enrollments' : IDL.Nat,
  'total_approved_hours' : IDL.Float64,
  'submitted_activities' : IDL.Nat,
  'global_qre_value' : IDL.Float64,
});
export const CreateRetroSessionInput = IDL.Record({
  'time_range_end' : IDL.Text,
  'time_range_start' : IDL.Text,
});

export const idlService = IDL.Service({
  'add_retro_message' : IDL.Func([AddRetroMessageInput], [RetroSession], []),
  'admin_create_program' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [RNDProgram],
      [],
    ),
  'admin_list_activities' : IDL.Func(
      [IDL.Opt(UserId), IDL.Opt(ActivityStatus), IDL.Opt(EntityId)],
      [IDL.Vec(RDActivity)],
      ['query'],
    ),
  'admin_list_enrollments' : IDL.Func(
      [IDL.Opt(EnrollmentStatus)],
      [IDL.Vec(Enrollment)],
      ['query'],
    ),
  'admin_list_users' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'admin_review_activity' : IDL.Func(
      [EntityId, ActivityStatus, IDL.Opt(IDL.Text)],
      [RDActivity],
      [],
    ),
  'admin_review_enrollment' : IDL.Func(
      [EntityId, EnrollmentStatus, IDL.Opt(IDL.Text)],
      [Enrollment],
      [],
    ),
  'admin_set_user_role' : IDL.Func([UserId, Role], [UserProfile], []),
  'complete_retro_session' : IDL.Func([EntityId], [RetroSession], []),
  'create_activity' : IDL.Func(
      [CreateActivityInput],
      [CreateActivityResult],
      [],
    ),
  'create_experiment' : IDL.Func([CreateExperimentInput], [Experiment], []),
  'enroll_in_program' : IDL.Func([EntityId], [Enrollment], []),
  'export_report_csv' : IDL.Func([EntityId], [IDL.Text], ['query']),
  'generate_global_report' : IDL.Func([IDL.Text, IDL.Text], [Report], []),
  'generate_user_report' : IDL.Func([UserId, IDL.Text, IDL.Text], [Report], []),
  'get_audit_trail' : IDL.Func(
      [EntityId, IDL.Nat],
      [IDL.Vec(AuditEntry)],
      ['query'],
    ),
  'get_global_stats' : IDL.Func([], [GlobalStats], ['query']),
  'get_my_profile' : IDL.Func([], [UserProfile], ['query']),
  'list_my_activities' : IDL.Func(
      [IDL.Opt(ActivityStatus), IDL.Opt(EntityId)],
      [IDL.Vec(RDActivity)],
      ['query'],
    ),
  'list_my_experiments' : IDL.Func([], [IDL.Vec(Experiment)], ['query']),
  'list_programs' : IDL.Func([], [IDL.Vec(RNDProgram)], ['query']),
  'list_retro_sessions' : IDL.Func([], [IDL.Vec(RetroSession)], ['query']),
  'start_retro_session' : IDL.Func(
      [CreateRetroSessionInput],
      [RetroSession],
      [],
    ),
  'update_experiment' : IDL.Func(
      [EntityId, CreateExperimentInput],
      [Experiment],
      [],
    ),
  'upsert_profile' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EntityId = IDL.Text;
  const AddRetroMessageInput = IDL.Record({
    'content' : IDL.Text,
    'session_id' : EntityId,
    'role' : IDL.Text,
  });
  const RetroSessionStatus = IDL.Variant({
    'active' : IDL.Null,
    'completed' : IDL.Null,
  });
  const UserId = IDL.Text;
  const Timestamp = IDL.Nat64;
  const ConversationEntry = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const ActivityStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'retroactive' : IDL.Null,
    'ongoing' : IDL.Null,
  });
  const EligibilityLabel = IDL.Variant({
    'borderline' : IDL.Null,
    'ineligible' : IDL.Null,
    'eligible' : IDL.Null,
  });
  const FourPartTestResult = IDL.Record({
    'elimination_of_uncertainty' : IDL.Bool,
    'permitted_purpose' : IDL.Bool,
    'notes' : IDL.Text,
    'technological_in_nature' : IDL.Bool,
    'process_of_experimentation' : IDL.Bool,
  });
  const RDActivity = IDL.Record({
    'id' : EntityId,
    'status' : ActivityStatus,
    'activity_type' : ActivityType,
    'user_principal' : UserId,
    'title' : IDL.Text,
    'updated_at' : Timestamp,
    'content_hash' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'program_id' : IDL.Opt(EntityId),
    'description' : IDL.Text,
    'end_date' : IDL.Opt(IDL.Text),
    'eligibility_label' : EligibilityLabel,
    'created_at' : Timestamp,
    'eligibility_score' : IDL.Float64,
    'quantum_adjusted_score' : IDL.Float64,
    'start_date' : IDL.Text,
    'admin_notes' : IDL.Opt(IDL.Text),
    'agent_reasoning' : IDL.Text,
    'hours_spent' : IDL.Float64,
    'four_part_test_result' : FourPartTestResult,
  });
  const RetroSession = IDL.Record({
    'id' : EntityId,
    'status' : RetroSessionStatus,
    'user_principal' : UserId,
    'updated_at' : Timestamp,
    'time_range_end' : IDL.Text,
    'conversation' : IDL.Vec(ConversationEntry),
    'created_at' : Timestamp,
    'candidate_activities' : IDL.Vec(RDActivity),
    'time_range_start' : IDL.Text,
  });
  const ProgramStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const RNDProgram = IDL.Record({
    'id' : EntityId,
    'status' : ProgramStatus,
    'updated_at' : Timestamp,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'created_at' : Timestamp,
    'irc_section' : IDL.Text,
  });
  const EnrollmentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Enrollment = IDL.Record({
    'id' : EntityId,
    'status' : EnrollmentStatus,
    'user_principal' : UserId,
    'program_id' : EntityId,
    'enrolled_at' : Timestamp,
    'reviewed_at' : IDL.Opt(Timestamp),
    'reviewed_by' : IDL.Opt(UserId),
    'review_notes' : IDL.Opt(IDL.Text),
  });
  const Role = IDL.Variant({ 'admin' : IDL.Null, 'user' : IDL.Null });
  const UserProfile = IDL.Record({
    'updated_at' : Timestamp,
    'role' : Role,
    'created_at' : Timestamp,
    'email' : IDL.Opt(IDL.Text),
    'principal_id' : UserId,
  });
  const CreateActivityInput = IDL.Record({
    'activity_type' : ActivityType,
    'title' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'program_id' : IDL.Opt(EntityId),
    'description' : IDL.Text,
    'end_date' : IDL.Opt(IDL.Text),
    'start_date' : IDL.Text,
    'hours_spent' : IDL.Float64,
  });
  const Recommendation = IDL.Variant({
    'reject' : IDL.Null,
    'approve' : IDL.Null,
    'more_info' : IDL.Null,
  });
  const AdminSuggestion = IDL.Record({
    'notes' : IDL.Text,
    'recommendation' : Recommendation,
    'confidence' : IDL.Nat,
  });
  const ClassificationResult = IDL.Record({
    'eligibility_label' : EligibilityLabel,
    'eligibility_score' : IDL.Float64,
    'quantum_adjusted_score' : IDL.Float64,
    'four_part_test' : FourPartTestResult,
    'suggested_tags' : IDL.Vec(IDL.Text),
    'admin_suggestion' : AdminSuggestion,
    'agent_reasoning' : IDL.Text,
  });
  const CreateActivityResult = IDL.Record({
    'activity' : RDActivity,
    'classification' : ClassificationResult,
  });
  const MetricEntry = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const ExperimentOutcome = IDL.Variant({
    'failure' : IDL.Null,
    'inconclusive' : IDL.Null,
    'success' : IDL.Null,
  });
  const CreateExperimentInput = IDL.Record({
    'method' : IDL.Text,
    'metrics' : IDL.Vec(MetricEntry),
    'linked_activity_id' : IDL.Opt(EntityId),
    'program_id' : IDL.Opt(EntityId),
    'hypothesis' : IDL.Text,
    'results_summary' : IDL.Text,
    'outcome' : ExperimentOutcome,
  });
  const Experiment = IDL.Record({
    'id' : EntityId,
    'method' : IDL.Text,
    'user_principal' : UserId,
    'updated_at' : Timestamp,
    'metrics' : IDL.Vec(MetricEntry),
    'linked_activity_id' : IDL.Opt(EntityId),
    'program_id' : IDL.Opt(EntityId),
    'hypothesis' : IDL.Text,
    'created_at' : Timestamp,
    'results_summary' : IDL.Text,
    'outcome' : ExperimentOutcome,
  });
  const ReportScope = IDL.Variant({ 'user' : IDL.Null, 'global' : IDL.Null });
  const Report = IDL.Record({
    'id' : EntityId,
    'period_end' : IDL.Text,
    'activity_ids' : IDL.Vec(EntityId),
    'generated_at' : Timestamp,
    'period_start' : IDL.Text,
    'eligible_hours' : IDL.Float64,
    'scope' : ReportScope,
    'total_hours' : IDL.Float64,
    'breakdown_borderline' : IDL.Nat,
    'breakdown_ineligible' : IDL.Nat,
    'estimated_qre_value' : IDL.Float64,
    'breakdown_eligible' : IDL.Nat,
  });
  const AuditEntry = IDL.Record({
    'id' : EntityId,
    'action' : IDL.Text,
    'timestamp' : Timestamp,
    'actor_principal' : UserId,
    'entity_id' : EntityId,
    'entity_type' : IDL.Text,
  });
  const GlobalStats = IDL.Record({
    'total_programs' : IDL.Nat,
    'total_users' : IDL.Nat,
    'pending_enrollments' : IDL.Nat,
    'total_approved_hours' : IDL.Float64,
    'submitted_activities' : IDL.Nat,
    'global_qre_value' : IDL.Float64,
  });
  const CreateRetroSessionInput = IDL.Record({
    'time_range_end' : IDL.Text,
    'time_range_start' : IDL.Text,
  });
  
  return IDL.Service({
    'add_retro_message' : IDL.Func([AddRetroMessageInput], [RetroSession], []),
    'admin_create_program' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [RNDProgram],
        [],
      ),
    'admin_list_activities' : IDL.Func(
        [IDL.Opt(UserId), IDL.Opt(ActivityStatus), IDL.Opt(EntityId)],
        [IDL.Vec(RDActivity)],
        ['query'],
      ),
    'admin_list_enrollments' : IDL.Func(
        [IDL.Opt(EnrollmentStatus)],
        [IDL.Vec(Enrollment)],
        ['query'],
      ),
    'admin_list_users' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'admin_review_activity' : IDL.Func(
        [EntityId, ActivityStatus, IDL.Opt(IDL.Text)],
        [RDActivity],
        [],
      ),
    'admin_review_enrollment' : IDL.Func(
        [EntityId, EnrollmentStatus, IDL.Opt(IDL.Text)],
        [Enrollment],
        [],
      ),
    'admin_set_user_role' : IDL.Func([UserId, Role], [UserProfile], []),
    'complete_retro_session' : IDL.Func([EntityId], [RetroSession], []),
    'create_activity' : IDL.Func(
        [CreateActivityInput],
        [CreateActivityResult],
        [],
      ),
    'create_experiment' : IDL.Func([CreateExperimentInput], [Experiment], []),
    'enroll_in_program' : IDL.Func([EntityId], [Enrollment], []),
    'export_report_csv' : IDL.Func([EntityId], [IDL.Text], ['query']),
    'generate_global_report' : IDL.Func([IDL.Text, IDL.Text], [Report], []),
    'generate_user_report' : IDL.Func(
        [UserId, IDL.Text, IDL.Text],
        [Report],
        [],
      ),
    'get_audit_trail' : IDL.Func(
        [EntityId, IDL.Nat],
        [IDL.Vec(AuditEntry)],
        ['query'],
      ),
    'get_global_stats' : IDL.Func([], [GlobalStats], ['query']),
    'get_my_profile' : IDL.Func([], [UserProfile], ['query']),
    'list_my_activities' : IDL.Func(
        [IDL.Opt(ActivityStatus), IDL.Opt(EntityId)],
        [IDL.Vec(RDActivity)],
        ['query'],
      ),
    'list_my_experiments' : IDL.Func([], [IDL.Vec(Experiment)], ['query']),
    'list_programs' : IDL.Func([], [IDL.Vec(RNDProgram)], ['query']),
    'list_retro_sessions' : IDL.Func([], [IDL.Vec(RetroSession)], ['query']),
    'start_retro_session' : IDL.Func(
        [CreateRetroSessionInput],
        [RetroSession],
        [],
      ),
    'update_experiment' : IDL.Func(
        [EntityId, CreateExperimentInput],
        [Experiment],
        [],
      ),
    'upsert_profile' : IDL.Func([IDL.Opt(IDL.Text)], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };