/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ActivityStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null };
export type ActivityType = { 'retroactive' : null } |
  { 'ongoing' : null };
export interface AddRetroMessageInput {
  'content' : string,
  'session_id' : EntityId,
  'role' : string,
}
export interface AdminSuggestion {
  'notes' : string,
  'recommendation' : Recommendation,
  'confidence' : bigint,
}
export interface AuditEntry {
  'id' : EntityId,
  'action' : string,
  'timestamp' : Timestamp,
  'actor_principal' : UserId,
  'entity_id' : EntityId,
  'entity_type' : string,
}
export interface ClassificationResult {
  'eligibility_label' : EligibilityLabel,
  'eligibility_score' : number,
  'quantum_adjusted_score' : number,
  'four_part_test' : FourPartTestResult,
  'suggested_tags' : Array<string>,
  'admin_suggestion' : AdminSuggestion,
  'agent_reasoning' : string,
}
export interface ConversationEntry {
  'content' : string,
  'role' : string,
  'timestamp' : Timestamp,
}
export interface CreateActivityInput {
  'activity_type' : ActivityType,
  'title' : string,
  'tags' : Array<string>,
  'program_id' : [] | [EntityId],
  'description' : string,
  'end_date' : [] | [string],
  'start_date' : string,
  'hours_spent' : number,
}
export interface CreateActivityResult {
  'activity' : RDActivity,
  'classification' : ClassificationResult,
}
export interface CreateExperimentInput {
  'method' : string,
  'metrics' : Array<MetricEntry>,
  'linked_activity_id' : [] | [EntityId],
  'program_id' : [] | [EntityId],
  'hypothesis' : string,
  'results_summary' : string,
  'outcome' : ExperimentOutcome,
}
export interface CreateRetroSessionInput {
  'time_range_end' : string,
  'time_range_start' : string,
}
export type EligibilityLabel = { 'borderline' : null } |
  { 'ineligible' : null } |
  { 'eligible' : null };
export interface Enrollment {
  'id' : EntityId,
  'status' : EnrollmentStatus,
  'user_principal' : UserId,
  'program_id' : EntityId,
  'enrolled_at' : Timestamp,
  'reviewed_at' : [] | [Timestamp],
  'reviewed_by' : [] | [UserId],
  'review_notes' : [] | [string],
}
export type EnrollmentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type EntityId = string;
export interface Experiment {
  'id' : EntityId,
  'method' : string,
  'user_principal' : UserId,
  'updated_at' : Timestamp,
  'metrics' : Array<MetricEntry>,
  'linked_activity_id' : [] | [EntityId],
  'program_id' : [] | [EntityId],
  'hypothesis' : string,
  'created_at' : Timestamp,
  'results_summary' : string,
  'outcome' : ExperimentOutcome,
}
export type ExperimentOutcome = { 'failure' : null } |
  { 'inconclusive' : null } |
  { 'success' : null };
export interface FourPartTestResult {
  'elimination_of_uncertainty' : boolean,
  'permitted_purpose' : boolean,
  'notes' : string,
  'technological_in_nature' : boolean,
  'process_of_experimentation' : boolean,
}
export interface GlobalStats {
  'total_programs' : bigint,
  'total_users' : bigint,
  'pending_enrollments' : bigint,
  'total_approved_hours' : number,
  'submitted_activities' : bigint,
  'global_qre_value' : number,
}
export interface MetricEntry { 'value' : string, 'name' : string }
export type ProgramStatus = { 'active' : null } |
  { 'inactive' : null };
export interface RDActivity {
  'id' : EntityId,
  'status' : ActivityStatus,
  'activity_type' : ActivityType,
  'user_principal' : UserId,
  'title' : string,
  'updated_at' : Timestamp,
  'content_hash' : string,
  'tags' : Array<string>,
  'program_id' : [] | [EntityId],
  'description' : string,
  'end_date' : [] | [string],
  'eligibility_label' : EligibilityLabel,
  'created_at' : Timestamp,
  'eligibility_score' : number,
  'quantum_adjusted_score' : number,
  'start_date' : string,
  'admin_notes' : [] | [string],
  'agent_reasoning' : string,
  'hours_spent' : number,
  'four_part_test_result' : FourPartTestResult,
}
export interface RNDProgram {
  'id' : EntityId,
  'status' : ProgramStatus,
  'updated_at' : Timestamp,
  'name' : string,
  'description' : string,
  'created_at' : Timestamp,
  'irc_section' : string,
}
export type Recommendation = { 'reject' : null } |
  { 'approve' : null } |
  { 'more_info' : null };
export interface Report {
  'id' : EntityId,
  'period_end' : string,
  'activity_ids' : Array<EntityId>,
  'generated_at' : Timestamp,
  'period_start' : string,
  'eligible_hours' : number,
  'scope' : ReportScope,
  'total_hours' : number,
  'breakdown_borderline' : bigint,
  'breakdown_ineligible' : bigint,
  'estimated_qre_value' : number,
  'breakdown_eligible' : bigint,
}
export type ReportScope = { 'user' : null } |
  { 'global' : null };
export interface RetroSession {
  'id' : EntityId,
  'status' : RetroSessionStatus,
  'user_principal' : UserId,
  'updated_at' : Timestamp,
  'time_range_end' : string,
  'conversation' : Array<ConversationEntry>,
  'created_at' : Timestamp,
  'candidate_activities' : Array<RDActivity>,
  'time_range_start' : string,
}
export type RetroSessionStatus = { 'active' : null } |
  { 'completed' : null };
export type Role = { 'admin' : null } |
  { 'user' : null };
export type Timestamp = bigint;
export type UserId = string;
export interface UserProfile {
  'updated_at' : Timestamp,
  'role' : Role,
  'created_at' : Timestamp,
  'email' : [] | [string],
  'principal_id' : UserId,
}
export interface _SERVICE {
  'add_retro_message' : ActorMethod<[AddRetroMessageInput], RetroSession>,
  'admin_create_program' : ActorMethod<
    [string, string, [] | [string]],
    RNDProgram
  >,
  'admin_list_activities' : ActorMethod<
    [[] | [UserId], [] | [ActivityStatus], [] | [EntityId]],
    Array<RDActivity>
  >,
  'admin_list_enrollments' : ActorMethod<
    [[] | [EnrollmentStatus]],
    Array<Enrollment>
  >,
  'admin_list_users' : ActorMethod<[], Array<UserProfile>>,
  'admin_review_activity' : ActorMethod<
    [EntityId, ActivityStatus, [] | [string]],
    RDActivity
  >,
  'admin_review_enrollment' : ActorMethod<
    [EntityId, EnrollmentStatus, [] | [string]],
    Enrollment
  >,
  'admin_set_user_role' : ActorMethod<[UserId, Role], UserProfile>,
  'complete_retro_session' : ActorMethod<[EntityId], RetroSession>,
  'create_activity' : ActorMethod<[CreateActivityInput], CreateActivityResult>,
  'create_experiment' : ActorMethod<[CreateExperimentInput], Experiment>,
  'enroll_in_program' : ActorMethod<[EntityId], Enrollment>,
  'export_report_csv' : ActorMethod<[EntityId], string>,
  'generate_global_report' : ActorMethod<[string, string], Report>,
  'generate_user_report' : ActorMethod<[UserId, string, string], Report>,
  'get_audit_trail' : ActorMethod<[EntityId, bigint], Array<AuditEntry>>,
  'get_global_stats' : ActorMethod<[], GlobalStats>,
  'get_my_profile' : ActorMethod<[], UserProfile>,
  'list_my_activities' : ActorMethod<
    [[] | [ActivityStatus], [] | [EntityId]],
    Array<RDActivity>
  >,
  'list_my_experiments' : ActorMethod<[], Array<Experiment>>,
  'list_programs' : ActorMethod<[], Array<RNDProgram>>,
  'list_retro_sessions' : ActorMethod<[], Array<RetroSession>>,
  'start_retro_session' : ActorMethod<[CreateRetroSessionInput], RetroSession>,
  'update_experiment' : ActorMethod<
    [EntityId, CreateExperimentInput],
    Experiment
  >,
  'upsert_profile' : ActorMethod<[[] | [string]], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];