/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface RNDProgram {
    id: EntityId;
    status: ProgramStatus;
    updated_at: Timestamp;
    name: string;
    description: string;
    created_at: Timestamp;
    irc_section: string;
}
export interface ConversationEntry {
    content: string;
    role: string;
    timestamp: Timestamp;
}
export type EntityId = string;
export interface FourPartTestResult {
    elimination_of_uncertainty: boolean;
    permitted_purpose: boolean;
    notes: string;
    technological_in_nature: boolean;
    process_of_experimentation: boolean;
}
export interface Enrollment {
    id: EntityId;
    status: EnrollmentStatus;
    user_principal: UserId;
    program_id: EntityId;
    enrolled_at: Timestamp;
    reviewed_at?: Timestamp;
    reviewed_by?: UserId;
    review_notes?: string;
}
export interface CreateActivityResult {
    activity: RDActivity;
    classification: ClassificationResult;
}
export interface Report {
    id: EntityId;
    period_end: string;
    activity_ids: Array<EntityId>;
    generated_at: Timestamp;
    period_start: string;
    eligible_hours: number;
    scope: ReportScope;
    total_hours: number;
    breakdown_borderline: bigint;
    breakdown_ineligible: bigint;
    estimated_qre_value: number;
    breakdown_eligible: bigint;
}
export interface CreateRetroSessionInput {
    time_range_end: string;
    time_range_start: string;
}
export interface MetricEntry {
    value: string;
    name: string;
}
export interface CreateExperimentInput {
    method: string;
    metrics: Array<MetricEntry>;
    linked_activity_id?: EntityId;
    program_id?: EntityId;
    hypothesis: string;
    results_summary: string;
    outcome: ExperimentOutcome;
}
export interface AuditEntry {
    id: EntityId;
    action: string;
    timestamp: Timestamp;
    actor_principal: UserId;
    entity_id: EntityId;
    entity_type: string;
}
export interface GlobalStats {
    total_programs: bigint;
    total_users: bigint;
    pending_enrollments: bigint;
    total_approved_hours: number;
    submitted_activities: bigint;
    global_qre_value: number;
}
export interface AdminSuggestion {
    notes: string;
    recommendation: Recommendation;
    confidence: bigint;
}
export interface AddRetroMessageInput {
    content: string;
    session_id: EntityId;
    role: string;
}
export type UserId = string;
export interface ClassificationResult {
    eligibility_label: EligibilityLabel;
    eligibility_score: number;
    quantum_adjusted_score: number;
    four_part_test: FourPartTestResult;
    suggested_tags: Array<string>;
    admin_suggestion: AdminSuggestion;
    agent_reasoning: string;
}
export interface RetroSession {
    id: EntityId;
    status: RetroSessionStatus;
    user_principal: UserId;
    updated_at: Timestamp;
    time_range_end: string;
    conversation: Array<ConversationEntry>;
    created_at: Timestamp;
    candidate_activities: Array<RDActivity>;
    time_range_start: string;
}
export interface Experiment {
    id: EntityId;
    method: string;
    user_principal: UserId;
    updated_at: Timestamp;
    metrics: Array<MetricEntry>;
    linked_activity_id?: EntityId;
    program_id?: EntityId;
    hypothesis: string;
    created_at: Timestamp;
    results_summary: string;
    outcome: ExperimentOutcome;
}
export interface CreateActivityInput {
    activity_type: ActivityType;
    title: string;
    tags: Array<string>;
    program_id?: EntityId;
    description: string;
    end_date?: string;
    start_date: string;
    hours_spent: number;
}
export interface UserProfile {
    updated_at: Timestamp;
    role: Role;
    created_at: Timestamp;
    email?: string;
    principal_id: UserId;
}
export interface RDActivity {
    id: EntityId;
    status: ActivityStatus;
    activity_type: ActivityType;
    user_principal: UserId;
    title: string;
    updated_at: Timestamp;
    content_hash: string;
    tags: Array<string>;
    program_id?: EntityId;
    description: string;
    end_date?: string;
    eligibility_label: EligibilityLabel;
    created_at: Timestamp;
    eligibility_score: number;
    quantum_adjusted_score: number;
    start_date: string;
    admin_notes?: string;
    agent_reasoning: string;
    hours_spent: number;
    four_part_test_result: FourPartTestResult;
}
export enum ActivityStatus {
    submitted = "submitted",
    approved = "approved",
    rejected = "rejected",
    draft = "draft"
}
export enum ActivityType {
    retroactive = "retroactive",
    ongoing = "ongoing"
}
export enum EligibilityLabel {
    borderline = "borderline",
    ineligible = "ineligible",
    eligible = "eligible"
}
export enum EnrollmentStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum ExperimentOutcome {
    failure = "failure",
    inconclusive = "inconclusive",
    success = "success"
}
export enum ProgramStatus {
    active = "active",
    inactive = "inactive"
}
export enum Recommendation {
    reject = "reject",
    approve = "approve",
    more_info = "more_info"
}
export enum ReportScope {
    user = "user",
    global = "global"
}
export enum RetroSessionStatus {
    active = "active",
    completed = "completed"
}
export enum Role {
    admin = "admin",
    user = "user"
}
export interface backendInterface {
    add_retro_message(input: AddRetroMessageInput): Promise<RetroSession>;
    admin_create_program(name: string, description: string, irc_section: string | null): Promise<RNDProgram>;
    admin_list_activities(user_principal_filter: UserId | null, status_filter: ActivityStatus | null, program_id_filter: EntityId | null): Promise<Array<RDActivity>>;
    admin_list_enrollments(status_filter: EnrollmentStatus | null): Promise<Array<Enrollment>>;
    admin_list_users(): Promise<Array<UserProfile>>;
    admin_review_activity(id: EntityId, decision: ActivityStatus, notes: string | null): Promise<RDActivity>;
    admin_review_enrollment(id: EntityId, decision: EnrollmentStatus, notes: string | null): Promise<Enrollment>;
    admin_set_user_role(target_principal: UserId, role: Role): Promise<UserProfile>;
    complete_retro_session(session_id: EntityId): Promise<RetroSession>;
    create_activity(input: CreateActivityInput): Promise<CreateActivityResult>;
    create_experiment(input: CreateExperimentInput): Promise<Experiment>;
    enroll_in_program(program_id: EntityId): Promise<Enrollment>;
    export_report_csv(report_id: EntityId): Promise<string>;
    generate_global_report(period_start: string, period_end: string): Promise<Report>;
    generate_user_report(user_principal: UserId, period_start: string, period_end: string): Promise<Report>;
    get_audit_trail(entity_id: EntityId, limit: bigint): Promise<Array<AuditEntry>>;
    get_global_stats(): Promise<GlobalStats>;
    get_my_profile(): Promise<UserProfile>;
    list_my_activities(status_filter: ActivityStatus | null, program_id_filter: EntityId | null): Promise<Array<RDActivity>>;
    list_my_experiments(): Promise<Array<Experiment>>;
    list_programs(): Promise<Array<RNDProgram>>;
    list_retro_sessions(): Promise<Array<RetroSession>>;
    start_retro_session(input: CreateRetroSessionInput): Promise<RetroSession>;
    update_experiment(id: EntityId, input: CreateExperimentInput): Promise<Experiment>;
    upsert_profile(email: string | null): Promise<UserProfile>;
}
import type { ActivityStatus as _ActivityStatus, ActivityType as _ActivityType, AdminSuggestion as _AdminSuggestion, ClassificationResult as _ClassificationResult, ConversationEntry as _ConversationEntry, CreateActivityInput as _CreateActivityInput, CreateActivityResult as _CreateActivityResult, CreateExperimentInput as _CreateExperimentInput, EligibilityLabel as _EligibilityLabel, Enrollment as _Enrollment, EnrollmentStatus as _EnrollmentStatus, EntityId as _EntityId, Experiment as _Experiment, ExperimentOutcome as _ExperimentOutcome, FourPartTestResult as _FourPartTestResult, MetricEntry as _MetricEntry, ProgramStatus as _ProgramStatus, RDActivity as _RDActivity, RNDProgram as _RNDProgram, Recommendation as _Recommendation, Report as _Report, ReportScope as _ReportScope, RetroSession as _RetroSession, RetroSessionStatus as _RetroSessionStatus, Role as _Role, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async add_retro_message(arg0: AddRetroMessageInput): Promise<RetroSession> {
        if (this.processError) {
            try {
                const result = await this.actor.add_retro_message(arg0);
                return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.add_retro_message(arg0);
            return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_create_program(arg0: string, arg1: string, arg2: string | null): Promise<RNDProgram> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_create_program(arg0, arg1, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
                return from_candid_RNDProgram_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_create_program(arg0, arg1, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
            return from_candid_RNDProgram_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_list_activities(arg0: UserId | null, arg1: ActivityStatus | null, arg2: EntityId | null): Promise<Array<RDActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_list_activities(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_list_activities(to_candid_opt_n21(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n22(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_list_enrollments(arg0: EnrollmentStatus | null): Promise<Array<Enrollment>> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_list_enrollments(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_list_enrollments(to_candid_opt_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_list_users(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_list_users();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_list_users();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_review_activity(arg0: EntityId, arg1: ActivityStatus, arg2: string | null): Promise<RDActivity> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_review_activity(arg0, to_candid_ActivityStatus_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
                return from_candid_RDActivity_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_review_activity(arg0, to_candid_ActivityStatus_n23(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
            return from_candid_RDActivity_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_review_enrollment(arg0: EntityId, arg1: EnrollmentStatus, arg2: string | null): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_review_enrollment(arg0, to_candid_EnrollmentStatus_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_review_enrollment(arg0, to_candid_EnrollmentStatus_n27(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async admin_set_user_role(arg0: UserId, arg1: Role): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.admin_set_user_role(arg0, to_candid_Role_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.admin_set_user_role(arg0, to_candid_Role_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async complete_retro_session(arg0: EntityId): Promise<RetroSession> {
        if (this.processError) {
            try {
                const result = await this.actor.complete_retro_session(arg0);
                return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.complete_retro_session(arg0);
            return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async create_activity(arg0: CreateActivityInput): Promise<CreateActivityResult> {
        if (this.processError) {
            try {
                const result = await this.actor.create_activity(to_candid_CreateActivityInput_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CreateActivityResult_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_activity(to_candid_CreateActivityInput_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CreateActivityResult_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async create_experiment(arg0: CreateExperimentInput): Promise<Experiment> {
        if (this.processError) {
            try {
                const result = await this.actor.create_experiment(to_candid_CreateExperimentInput_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Experiment_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.create_experiment(to_candid_CreateExperimentInput_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Experiment_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async enroll_in_program(arg0: EntityId): Promise<Enrollment> {
        if (this.processError) {
            try {
                const result = await this.actor.enroll_in_program(arg0);
                return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.enroll_in_program(arg0);
            return from_candid_Enrollment_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async export_report_csv(arg0: EntityId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.export_report_csv(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.export_report_csv(arg0);
            return result;
        }
    }
    async generate_global_report(arg0: string, arg1: string): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generate_global_report(arg0, arg1);
                return from_candid_Report_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generate_global_report(arg0, arg1);
            return from_candid_Report_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async generate_user_report(arg0: UserId, arg1: string, arg2: string): Promise<Report> {
        if (this.processError) {
            try {
                const result = await this.actor.generate_user_report(arg0, arg1, arg2);
                return from_candid_Report_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generate_user_report(arg0, arg1, arg2);
            return from_candid_Report_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async get_audit_trail(arg0: EntityId, arg1: bigint): Promise<Array<AuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.get_audit_trail(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_audit_trail(arg0, arg1);
            return result;
        }
    }
    async get_global_stats(): Promise<GlobalStats> {
        if (this.processError) {
            try {
                const result = await this.actor.get_global_stats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_global_stats();
            return result;
        }
    }
    async get_my_profile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.get_my_profile();
                return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.get_my_profile();
            return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async list_my_activities(arg0: ActivityStatus | null, arg1: EntityId | null): Promise<Array<RDActivity>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_my_activities(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_my_activities(to_candid_opt_n22(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async list_my_experiments(): Promise<Array<Experiment>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_my_experiments();
                return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_my_experiments();
            return from_candid_vec_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async list_programs(): Promise<Array<RNDProgram>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_programs();
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_programs();
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async list_retro_sessions(): Promise<Array<RetroSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.list_retro_sessions();
                return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.list_retro_sessions();
            return from_candid_vec_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async start_retro_session(arg0: CreateRetroSessionInput): Promise<RetroSession> {
        if (this.processError) {
            try {
                const result = await this.actor.start_retro_session(arg0);
                return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.start_retro_session(arg0);
            return from_candid_RetroSession_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async update_experiment(arg0: EntityId, arg1: CreateExperimentInput): Promise<Experiment> {
        if (this.processError) {
            try {
                const result = await this.actor.update_experiment(arg0, to_candid_CreateExperimentInput_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Experiment_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.update_experiment(arg0, to_candid_CreateExperimentInput_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Experiment_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async upsert_profile(arg0: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsert_profile(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsert_profile(to_candid_opt_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n37(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ActivityStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityStatus): ActivityStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ActivityType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_AdminSuggestion_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdminSuggestion): AdminSuggestion {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_ClassificationResult_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ClassificationResult): ClassificationResult {
    return from_candid_record_n50(_uploadFile, _downloadFile, value);
}
function from_candid_CreateActivityResult_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateActivityResult): CreateActivityResult {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_EligibilityLabel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EligibilityLabel): EligibilityLabel {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_EnrollmentStatus_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnrollmentStatus): EnrollmentStatus {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_Enrollment_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Enrollment): Enrollment {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_ExperimentOutcome_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperimentOutcome): ExperimentOutcome {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Experiment_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Experiment): Experiment {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_ProgramStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProgramStatus): ProgramStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RDActivity_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RDActivity): RDActivity {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_RNDProgram_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RNDProgram): RNDProgram {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Recommendation_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Recommendation): Recommendation {
    return from_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function from_candid_ReportScope_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReportScope): ReportScope {
    return from_candid_variant_n66(_uploadFile, _downloadFile, value);
}
function from_candid_Report_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Report): Report {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_RetroSessionStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetroSessionStatus): RetroSessionStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RetroSession_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RetroSession): RetroSession {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EntityId]): EntityId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _ProgramStatus;
    updated_at: _Timestamp;
    name: string;
    description: string;
    created_at: _Timestamp;
    irc_section: string;
}): {
    id: EntityId;
    status: ProgramStatus;
    updated_at: Timestamp;
    name: string;
    description: string;
    created_at: Timestamp;
    irc_section: string;
} {
    return {
        id: value.id,
        status: from_candid_ProgramStatus_n19(_uploadFile, _downloadFile, value.status),
        updated_at: value.updated_at,
        name: value.name,
        description: value.description,
        created_at: value.created_at,
        irc_section: value.irc_section
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _RetroSessionStatus;
    user_principal: _UserId;
    updated_at: _Timestamp;
    time_range_end: string;
    conversation: Array<_ConversationEntry>;
    created_at: _Timestamp;
    candidate_activities: Array<_RDActivity>;
    time_range_start: string;
}): {
    id: EntityId;
    status: RetroSessionStatus;
    user_principal: UserId;
    updated_at: Timestamp;
    time_range_end: string;
    conversation: Array<ConversationEntry>;
    created_at: Timestamp;
    candidate_activities: Array<RDActivity>;
    time_range_start: string;
} {
    return {
        id: value.id,
        status: from_candid_RetroSessionStatus_n3(_uploadFile, _downloadFile, value.status),
        user_principal: value.user_principal,
        updated_at: value.updated_at,
        time_range_end: value.time_range_end,
        conversation: value.conversation,
        created_at: value.created_at,
        candidate_activities: from_candid_vec_n5(_uploadFile, _downloadFile, value.candidate_activities),
        time_range_start: value.time_range_start
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _EnrollmentStatus;
    user_principal: _UserId;
    program_id: _EntityId;
    enrolled_at: _Timestamp;
    reviewed_at: [] | [_Timestamp];
    reviewed_by: [] | [_UserId];
    review_notes: [] | [string];
}): {
    id: EntityId;
    status: EnrollmentStatus;
    user_principal: UserId;
    program_id: EntityId;
    enrolled_at: Timestamp;
    reviewed_at?: Timestamp;
    reviewed_by?: UserId;
    review_notes?: string;
} {
    return {
        id: value.id,
        status: from_candid_EnrollmentStatus_n32(_uploadFile, _downloadFile, value.status),
        user_principal: value.user_principal,
        program_id: value.program_id,
        enrolled_at: value.enrolled_at,
        reviewed_at: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.reviewed_at)),
        reviewed_by: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.reviewed_by)),
        review_notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.review_notes))
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    updated_at: _Timestamp;
    role: _Role;
    created_at: _Timestamp;
    email: [] | [string];
    principal_id: _UserId;
}): {
    updated_at: Timestamp;
    role: Role;
    created_at: Timestamp;
    email?: string;
    principal_id: UserId;
} {
    return {
        updated_at: value.updated_at,
        role: from_candid_Role_n39(_uploadFile, _downloadFile, value.role),
        created_at: value.created_at,
        email: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.email)),
        principal_id: value.principal_id
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activity: _RDActivity;
    classification: _ClassificationResult;
}): {
    activity: RDActivity;
    classification: ClassificationResult;
} {
    return {
        activity: from_candid_RDActivity_n6(_uploadFile, _downloadFile, value.activity),
        classification: from_candid_ClassificationResult_n49(_uploadFile, _downloadFile, value.classification)
    };
}
function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    eligibility_label: _EligibilityLabel;
    eligibility_score: number;
    quantum_adjusted_score: number;
    four_part_test: _FourPartTestResult;
    suggested_tags: Array<string>;
    admin_suggestion: _AdminSuggestion;
    agent_reasoning: string;
}): {
    eligibility_label: EligibilityLabel;
    eligibility_score: number;
    quantum_adjusted_score: number;
    four_part_test: FourPartTestResult;
    suggested_tags: Array<string>;
    admin_suggestion: AdminSuggestion;
    agent_reasoning: string;
} {
    return {
        eligibility_label: from_candid_EligibilityLabel_n14(_uploadFile, _downloadFile, value.eligibility_label),
        eligibility_score: value.eligibility_score,
        quantum_adjusted_score: value.quantum_adjusted_score,
        four_part_test: value.four_part_test,
        suggested_tags: value.suggested_tags,
        admin_suggestion: from_candid_AdminSuggestion_n51(_uploadFile, _downloadFile, value.admin_suggestion),
        agent_reasoning: value.agent_reasoning
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notes: string;
    recommendation: _Recommendation;
    confidence: bigint;
}): {
    notes: string;
    recommendation: Recommendation;
    confidence: bigint;
} {
    return {
        notes: value.notes,
        recommendation: from_candid_Recommendation_n53(_uploadFile, _downloadFile, value.recommendation),
        confidence: value.confidence
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    method: string;
    user_principal: _UserId;
    updated_at: _Timestamp;
    metrics: Array<_MetricEntry>;
    linked_activity_id: [] | [_EntityId];
    program_id: [] | [_EntityId];
    hypothesis: string;
    created_at: _Timestamp;
    results_summary: string;
    outcome: _ExperimentOutcome;
}): {
    id: EntityId;
    method: string;
    user_principal: UserId;
    updated_at: Timestamp;
    metrics: Array<MetricEntry>;
    linked_activity_id?: EntityId;
    program_id?: EntityId;
    hypothesis: string;
    created_at: Timestamp;
    results_summary: string;
    outcome: ExperimentOutcome;
} {
    return {
        id: value.id,
        method: value.method,
        user_principal: value.user_principal,
        updated_at: value.updated_at,
        metrics: value.metrics,
        linked_activity_id: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.linked_activity_id)),
        program_id: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.program_id)),
        hypothesis: value.hypothesis,
        created_at: value.created_at,
        results_summary: value.results_summary,
        outcome: from_candid_ExperimentOutcome_n61(_uploadFile, _downloadFile, value.outcome)
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    period_end: string;
    activity_ids: Array<_EntityId>;
    generated_at: _Timestamp;
    period_start: string;
    eligible_hours: number;
    scope: _ReportScope;
    total_hours: number;
    breakdown_borderline: bigint;
    breakdown_ineligible: bigint;
    estimated_qre_value: number;
    breakdown_eligible: bigint;
}): {
    id: EntityId;
    period_end: string;
    activity_ids: Array<EntityId>;
    generated_at: Timestamp;
    period_start: string;
    eligible_hours: number;
    scope: ReportScope;
    total_hours: number;
    breakdown_borderline: bigint;
    breakdown_ineligible: bigint;
    estimated_qre_value: number;
    breakdown_eligible: bigint;
} {
    return {
        id: value.id,
        period_end: value.period_end,
        activity_ids: value.activity_ids,
        generated_at: value.generated_at,
        period_start: value.period_start,
        eligible_hours: value.eligible_hours,
        scope: from_candid_ReportScope_n65(_uploadFile, _downloadFile, value.scope),
        total_hours: value.total_hours,
        breakdown_borderline: value.breakdown_borderline,
        breakdown_ineligible: value.breakdown_ineligible,
        estimated_qre_value: value.estimated_qre_value,
        breakdown_eligible: value.breakdown_eligible
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: _ActivityStatus;
    activity_type: _ActivityType;
    user_principal: _UserId;
    title: string;
    updated_at: _Timestamp;
    content_hash: string;
    tags: Array<string>;
    program_id: [] | [_EntityId];
    description: string;
    end_date: [] | [string];
    eligibility_label: _EligibilityLabel;
    created_at: _Timestamp;
    eligibility_score: number;
    quantum_adjusted_score: number;
    start_date: string;
    admin_notes: [] | [string];
    agent_reasoning: string;
    hours_spent: number;
    four_part_test_result: _FourPartTestResult;
}): {
    id: EntityId;
    status: ActivityStatus;
    activity_type: ActivityType;
    user_principal: UserId;
    title: string;
    updated_at: Timestamp;
    content_hash: string;
    tags: Array<string>;
    program_id?: EntityId;
    description: string;
    end_date?: string;
    eligibility_label: EligibilityLabel;
    created_at: Timestamp;
    eligibility_score: number;
    quantum_adjusted_score: number;
    start_date: string;
    admin_notes?: string;
    agent_reasoning: string;
    hours_spent: number;
    four_part_test_result: FourPartTestResult;
} {
    return {
        id: value.id,
        status: from_candid_ActivityStatus_n8(_uploadFile, _downloadFile, value.status),
        activity_type: from_candid_ActivityType_n10(_uploadFile, _downloadFile, value.activity_type),
        user_principal: value.user_principal,
        title: value.title,
        updated_at: value.updated_at,
        content_hash: value.content_hash,
        tags: value.tags,
        program_id: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.program_id)),
        description: value.description,
        end_date: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.end_date)),
        eligibility_label: from_candid_EligibilityLabel_n14(_uploadFile, _downloadFile, value.eligibility_label),
        created_at: value.created_at,
        eligibility_score: value.eligibility_score,
        quantum_adjusted_score: value.quantum_adjusted_score,
        start_date: value.start_date,
        admin_notes: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.admin_notes)),
        agent_reasoning: value.agent_reasoning,
        hours_spent: value.hours_spent,
        four_part_test_result: value.four_part_test_result
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    retroactive: null;
} | {
    ongoing: null;
}): ActivityType {
    return "retroactive" in value ? ActivityType.retroactive : "ongoing" in value ? ActivityType.ongoing : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    borderline: null;
} | {
    ineligible: null;
} | {
    eligible: null;
}): EligibilityLabel {
    return "borderline" in value ? EligibilityLabel.borderline : "ineligible" in value ? EligibilityLabel.ineligible : "eligible" in value ? EligibilityLabel.eligible : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): ProgramStatus {
    return "active" in value ? ProgramStatus.active : "inactive" in value ? ProgramStatus.inactive : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): EnrollmentStatus {
    return "pending" in value ? EnrollmentStatus.pending : "approved" in value ? EnrollmentStatus.approved : "rejected" in value ? EnrollmentStatus.rejected : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    completed: null;
}): RetroSessionStatus {
    return "active" in value ? RetroSessionStatus.active : "completed" in value ? RetroSessionStatus.completed : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
}): Role {
    return "admin" in value ? Role.admin : "user" in value ? Role.user : value;
}
function from_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    reject: null;
} | {
    approve: null;
} | {
    more_info: null;
}): Recommendation {
    return "reject" in value ? Recommendation.reject : "approve" in value ? Recommendation.approve : "more_info" in value ? Recommendation.more_info : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failure: null;
} | {
    inconclusive: null;
} | {
    success: null;
}): ExperimentOutcome {
    return "failure" in value ? ExperimentOutcome.failure : "inconclusive" in value ? ExperimentOutcome.inconclusive : "success" in value ? ExperimentOutcome.success : value;
}
function from_candid_variant_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: null;
} | {
    global: null;
}): ReportScope {
    return "user" in value ? ReportScope.user : "global" in value ? ReportScope.global : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
}): ActivityStatus {
    return "submitted" in value ? ActivityStatus.submitted : "approved" in value ? ActivityStatus.approved : "rejected" in value ? ActivityStatus.rejected : "draft" in value ? ActivityStatus.draft : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Enrollment>): Array<Enrollment> {
    return value.map((x)=>from_candid_Enrollment_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RDActivity>): Array<RDActivity> {
    return value.map((x)=>from_candid_RDActivity_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Experiment>): Array<Experiment> {
    return value.map((x)=>from_candid_Experiment_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RNDProgram>): Array<RNDProgram> {
    return value.map((x)=>from_candid_RNDProgram_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RetroSession>): Array<RetroSession> {
    return value.map((x)=>from_candid_RetroSession_n1(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): _ActivityStatus {
    return to_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function to_candid_ActivityType_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function to_candid_CreateActivityInput_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateActivityInput): _CreateActivityInput {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_CreateExperimentInput_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateExperimentInput): _CreateExperimentInput {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_EnrollmentStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentStatus): _EnrollmentStatus {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_ExperimentOutcome_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperimentOutcome): _ExperimentOutcome {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus | null): [] | [_ActivityStatus] {
    return value === null ? candid_none() : candid_some(to_candid_ActivityStatus_n23(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EntityId | null): [] | [_EntityId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentStatus | null): [] | [_EnrollmentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_EnrollmentStatus_n27(_uploadFile, _downloadFile, value));
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activity_type: ActivityType;
    title: string;
    tags: Array<string>;
    program_id?: EntityId;
    description: string;
    end_date?: string;
    start_date: string;
    hours_spent: number;
}): {
    activity_type: _ActivityType;
    title: string;
    tags: Array<string>;
    program_id: [] | [_EntityId];
    description: string;
    end_date: [] | [string];
    start_date: string;
    hours_spent: number;
} {
    return {
        activity_type: to_candid_ActivityType_n45(_uploadFile, _downloadFile, value.activity_type),
        title: value.title,
        tags: value.tags,
        program_id: value.program_id ? candid_some(value.program_id) : candid_none(),
        description: value.description,
        end_date: value.end_date ? candid_some(value.end_date) : candid_none(),
        start_date: value.start_date,
        hours_spent: value.hours_spent
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: string;
    metrics: Array<MetricEntry>;
    linked_activity_id?: EntityId;
    program_id?: EntityId;
    hypothesis: string;
    results_summary: string;
    outcome: ExperimentOutcome;
}): {
    method: string;
    metrics: Array<_MetricEntry>;
    linked_activity_id: [] | [_EntityId];
    program_id: [] | [_EntityId];
    hypothesis: string;
    results_summary: string;
    outcome: _ExperimentOutcome;
} {
    return {
        method: value.method,
        metrics: value.metrics,
        linked_activity_id: value.linked_activity_id ? candid_some(value.linked_activity_id) : candid_none(),
        program_id: value.program_id ? candid_some(value.program_id) : candid_none(),
        hypothesis: value.hypothesis,
        results_summary: value.results_summary,
        outcome: to_candid_ExperimentOutcome_n57(_uploadFile, _downloadFile, value.outcome)
    };
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityStatus): {
    submitted: null;
} | {
    approved: null;
} | {
    rejected: null;
} | {
    draft: null;
} {
    return value == ActivityStatus.submitted ? {
        submitted: null
    } : value == ActivityStatus.approved ? {
        approved: null
    } : value == ActivityStatus.rejected ? {
        rejected: null
    } : value == ActivityStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnrollmentStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == EnrollmentStatus.pending ? {
        pending: null
    } : value == EnrollmentStatus.approved ? {
        approved: null
    } : value == EnrollmentStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    user: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.user ? {
        user: null
    } : value;
}
function to_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    retroactive: null;
} | {
    ongoing: null;
} {
    return value == ActivityType.retroactive ? {
        retroactive: null
    } : value == ActivityType.ongoing ? {
        ongoing: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperimentOutcome): {
    failure: null;
} | {
    inconclusive: null;
} | {
    success: null;
} {
    return value == ExperimentOutcome.failure ? {
        failure: null
    } : value == ExperimentOutcome.inconclusive ? {
        inconclusive: null
    } : value == ExperimentOutcome.success ? {
        success: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
